### ISSUE TITLE
crah des modules 

### ISSUE THREAD

**Issue by CChalu** [wxgeo/geophar#2]
Bonjour,
Sur openSUSE Leap 15.1 et KDE, je souhaite utiliser Geophar en mode "portable"
Les modules tableaux, cryptographie et calculatrice se chargent et semblent fonctionner correctement. Par contre l'application ferme dès que j'essaie de charger le module traceur de courbe ou un autre module que ceux cités précédemment

Erreur obtenue en utilisant le bouton + pour ajouter
```
QSettings::value: Empty key passed
QSettings::value: Empty key passed
Démarrage GUI...
Arguments de la ligne de commande : {} []
Chargement des préférences...
Test de la version du fichier...
Modules à charger : ['bienvenue']
Import du module 'bienvenue'...
Test de la version du fichier...
Import du module 'tablatex'...
Test de la version du fichier...
Import du module 'calculatrice'...
Import du module 'cryptographie'...
Import du module 'traceur'...
Unhandled Python exception
KCrash: Application 'python3.6' crashing...
KCrash: Attempting to start /usr/lib64/libexec/drkonqi from kdeinit
sock_file=/run/user/1000/kdeinit5__0
QSocketNotifier: Invalid socket 8 and type 'Read', disabling...
Unable to start Dr. Konqi
Re-raising signal for core dump handling.
```
Erreur obtenue en utilisant Outils/options/modules pour ajouter :+1: 
````
QSettings::value: Empty key passed
QSettings::value: Empty key passed
Démarrage GUI...
Arguments de la ligne de commande : {} []
Chargement des préférences...
Test de la version du fichier...
Modules à charger : ['bienvenue']
Import du module 'bienvenue'...
Test de la version du fichier...
Modules à charger : ['bienvenue', 'calculatrice']
Import du module 'bienvenue'...
Import du module 'calculatrice'...
Modules à charger : ['bienvenue', 'calculatrice', 'cryptographie', 'tablatex']
Import du module 'bienvenue'...
Import du module 'calculatrice'...
Import du module 'cryptographie'...
Import du module 'tablatex'...
Test de la version du fichier...
Modules à charger : ['bienvenue', 'calculatrice', 'cryptographie', 'tablatex', 'traceur']
Import du module 'bienvenue'...
Import du module 'calculatrice'...
Import du module 'cryptographie'...
Import du module 'tablatex'...
Import du module 'traceur'...

** MODULE 'traceur' : ERREUR FATALE **

Traceback (most recent call last)
    File "/home/chalu/Téléchargements/geophar-master/wxgeometrie/GUI/onglets.py", line 311, in actualiser_liste_onglets
        self.nouvel_onglet(module._panel_(self, module), pos)
    File "/home/chalu/Téléchargements/geophar-master/wxgeometrie/modules/traceur/__init__.py", line 93, in __init__
        Panel_API_graphique.__init__(self, *args, **kw)
    File "/home/chalu/Téléchargements/geophar-master/wxgeometrie/GUI/panel.py", line 236, in __init__
        self.canvas = QtCanvas(self)
    File "/home/chalu/Téléchargements/geophar-master/wxgeometrie/GUI/qtcanvas.py", line 188, in __init__
        FigureCanvasQT.__init__(self, figure=self.figure)
    File "/usr/lib64/python3.6/site-packages/matplotlib/backends/backend_qt5.py", line 243, in __init__
        super(FigureCanvasQT, self).__init__(figure=figure)
TypeError: __init__() got an unexpected keyword argument 'figure'
Warning: this error was not raised.
```
+ Systeme:
     Version: Linux 4.12.14 lp151.28.4 default x86_64 with glibc2.3.4
     Repertoire:  /home/chalu/Téléchargements/geophar-master
     Processeur:  Intel core i5 CPU M 430 2.27GHz
     Distribution:  openSUSE Leap 15.1 avec KDE 5.12.8

+ Localisation:
     Langue:  fr_FR
     Encodage:  UTF-8

+ Python:
     Version: 3.6.5 (default, Mar 31 2018, 19:45:04) [GCC]
     Encodage:  utf-8 / Noms de fichiers: utf-8
     Executable:  /usr/bin/python3

+ PyQt:
     Version: Qt 5.9.7 (329991)
     Portage:  PyQt 5.11.3 (330499) 64 bits

+ Matplolib:
     Version: 2.0.2
     Tex:  False
     Numerix:  numpy (1.14.0)

+ Sympy:
     Version: 1.2

+ Géophar:
     Version: 18.08.2
     Session:  1560489756-3803258

Merci

**Comment by wxgeo** [comment]
Cela ressemble fortement à ce bug ci : https://github.com/matplotlib/matplotlib/issues/3623

Mais pour l'instant, je n'arrive pas à le reproduire...

J'ai installé openSUSE Leap 15.1 avec KDE 5.12.8 sous Virtualbox, mais l'activation d'un module graphique (géométrie, traceur de courbes, etc.) de géophar provoque un crash de python.

> nicolas@linux-kalw:~/Bureau> python3 geophar-18.08.2/geophar.pyw 
> QSettings::value: Empty key passed
> QSettings::value: Empty key passed
> Démarrage GUI...
> Arguments de la ligne de commande : {} []
> Modules à charger : ['bienvenue']
> Import du module 'bienvenue'...
> Géophar n'a pas été fermé correctement.
> Tentative de restauration de la session en cours...
> Warning: impossible de trouver la session précédente !
> Import du module 'surfaces'...
> Unhandled Python exception
> KCrash: Application 'python3.6' crashing...
> KCrash: Attempting to start /usr/lib64/libexec/drkonqi from kdeinit
> sock_file=/run/user/1000/kdeinit5__0

**Comment by CChalu** [comment]
Bonjour,
Oui l’ajout d’un module graphique provoque le crash. Le message d’erreur est un peu différent suivant que l’on utilise + ou le menu d’ajout.
Pensez à désactiver baloo qui effectue l’indexation des fichiers via configuration système > recherche car chez moi la répétition des crashs avait fini par corrompre la base de données d’indexation.
Merci pour vos recherches

Lucie

**Comment by wxgeo** [comment]
@CChalu 
Bonjour Lucie,
Pouvez-vous me dire si la nouvelle version résout ces problèmes ?
[](https://github.com/wxgeo/geophar/tree/v18.08.3)
En vous remerciant,
Nicolas

**Comment by wxgeo** [comment]
https://github.com/wxgeo/geophar/tree/v18.08.3

**Comment by CChalu** [comment]
Bonjour,
Non malheureusement toujours la même erreur.
erreur avec le bouton +

`Import du module 'traceur'...
Unhandled Python exception
KCrash: Application 'python3.6' crashing...
KCrash: Attempting to start /usr/lib64/libexec/drkonqi from kdeinit
sock_file=/run/user/1000/kdeinit5__0
QSocketNotifier: Invalid socket 7 and type 'Read', disabling...
Unable to start Dr. Konqi
Re-raising signal for core dump handling.
`
Et en passant par Outils > option> modules

`QSettings::value: Empty key passed
QSettings::value: Empty key passed
Démarrage GUI...
Création du répertoire : /home/chalu/Téléchargements/geophar-master/config/log
Création du répertoire : /home/chalu/Téléchargements/geophar-master/config/preferences
Création du répertoire : /home/chalu/Téléchargements/geophar-master/config/macros
Création du répertoire : /home/chalu/Téléchargements/geophar-master/config/session
Arguments de la ligne de commande : {} []
Modules à charger : ['bienvenue']
Import du module 'bienvenue'...
Modules à charger : ['bienvenue', 'tablatex']
Import du module 'bienvenue'...
Import du module 'tablatex'...
Modules à charger : ['bienvenue', 'tablatex', 'traceur']
Import du module 'bienvenue'...
Import du module 'tablatex'...
Import du module 'traceur'...

** MODULE 'traceur' : ERREUR FATALE **

Traceback (most recent call last)
    File "/home/chalu/Téléchargements/geophar-master/wxgeometrie/GUI/onglets.py", line 311, in actualiser_liste_onglets
        self.nouvel_onglet(module._panel_(self, module), pos)
    File "/home/chalu/Téléchargements/geophar-master/wxgeometrie/modules/traceur/__init__.py", line 93, in __init__
        Panel_API_graphique.__init__(self, *args, **kw)
    File "/home/chalu/Téléchargements/geophar-master/wxgeometrie/GUI/panel.py", line 236, in __init__
        self.canvas = QtCanvas(self)
    File "/home/chalu/Téléchargements/geophar-master/wxgeometrie/GUI/qtcanvas.py", line 188, in __init__
        FigureCanvasQT.__init__(self, figure=self.figure)
    File "/usr/lib64/python3.6/site-packages/matplotlib/backends/backend_qt5.py", line 243, in __init__
        super(FigureCanvasQT, self).__init__(figure=figure)
TypeError: __init__() got an unexpected keyword argument 'figure'
Warning: this error was not raised.

----------------------------------------------------
Le programme va redémarrer sans le module 'traceur'.
Veuillez patienter...
----------------------------------------------------
`
ça fonctionnait sous Virtualbox ? Merci pour tous vos efforts

**Comment by CChalu** [comment]
Bonsoir,
Non cette version ne fonctionne pas mieux, j'ai les mêmes erreurs me 
semble-t-il. Je les ai laissé sur github

**Comment by wxgeo** [comment]
Résumé des échanges par mail : 

- le problème est résolu en mettant à jour matplotlib : 
`pip3 install --upgrade --user matplotlib`
- reste la question du crash de l'application en passant par le bouton [+] (au lieu d'afficher un message d'erreur)
